//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveSessionHost.RDSHelper {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RDSHelper.IRDSProvisioning")]
    public interface IRDSProvisioning {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRDSProvisioning/BuildMeLS", ReplyAction="http://tempuri.org/IRDSProvisioning/BuildMeLSResponse")]
        void BuildMeLS(string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRDSProvisioning/BuildMeLS", ReplyAction="http://tempuri.org/IRDSProvisioning/BuildMeLSResponse")]
        System.Threading.Tasks.Task BuildMeLSAsync(string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRDSProvisioning/RemoveMeLS", ReplyAction="http://tempuri.org/IRDSProvisioning/RemoveMeLSResponse")]
        void RemoveMeLS(string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRDSProvisioning/RemoveMeLS", ReplyAction="http://tempuri.org/IRDSProvisioning/RemoveMeLSResponse")]
        System.Threading.Tasks.Task RemoveMeLSAsync(string _name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRDSProvisioningChannel : RemoveSessionHost.RDSHelper.IRDSProvisioning, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RDSProvisioningClient : System.ServiceModel.ClientBase<RemoveSessionHost.RDSHelper.IRDSProvisioning>, RemoveSessionHost.RDSHelper.IRDSProvisioning {
        
        public RDSProvisioningClient() {
        }
        
        public RDSProvisioningClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RDSProvisioningClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDSProvisioningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDSProvisioningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BuildMeLS(string _name) {
            base.Channel.BuildMeLS(_name);
        }
        
        public System.Threading.Tasks.Task BuildMeLSAsync(string _name) {
            return base.Channel.BuildMeLSAsync(_name);
        }
        
        public void RemoveMeLS(string _name) {
            base.Channel.RemoveMeLS(_name);
        }
        
        public System.Threading.Tasks.Task RemoveMeLSAsync(string _name) {
            return base.Channel.RemoveMeLSAsync(_name);
        }
    }
}
